<?php 
/**
 * views template to output one 'row' of a view.
 * This code was generated by the views theming wizard
 * Date: Sun, 09/16/2007 - 06:34
 * View: schedule
 *
 * Variables available:
 * $view -- the entire view object. Important parts of this object are
 *   schedule, .
 * $view_type -- The type of the view. Probably 'page' or 'block' but could
 *   also be 'embed' or other string passed in from a custom view creator.
 * $node -- the raw data. This is not a real node object, but will contain
 *   the nid as well as other support fields that might be necessary.
 * $count -- the current row in the view (not TOTAL but for this page) starting
 *   from 0.
 * $stripe -- 'odd' or 'even', alternating. * $field_home_team_nid -- 
 * $field_home_team_nid_label -- The assigned label for $field_home_team_nid
 * $field_visiting_team_nid -- 
 * $field_visiting_team_nid_label -- The assigned label for $field_visiting_team_nid
 * $field_date_value -- 
 * $field_date_value_label -- The assigned label for $field_date_value
 *
 * This function goes in your views-list-schedule.tpl.php file
 */

// get rid of <span class="date-display-single"> and </span>
$replace = array('<span class="date-display-single">', '</span>');
$field_date_value = str_replace($replace, "", $field_date_value) + (8 * 60 * 60);

$field_date_value = date('M d, Y - h:i A', (int) $field_date_value); 
 
 //now we add the stylesheet...
  drupal_add_css(path_to_theme() .'/views-list-schedule_date.css');
  
  ?>
<tr class="view-schedule-tr">
<td
class="view-data-field-gender-nid"><div class="view-field view-data-field-gender-value">
  <?php print $field_gender_value .' '. $field_sport_value?>
</div></td>
<td 
class="view-data-field-home-team-nid"><div class="view-field view-data-field-home-team-nid">
  <?php print $field_home_team_nid?>
</div></td>

<td class="view-data-field-visiting-team-nid"><div class="view-field view-data-field-visiting-team-nid">
  <?php print $field_visiting_team_nid?>
</div></td>

<td class="view-data-field-date-value"><div class="view-field view-data-field-date-value">
  <?php print $field_date_value?>
</div></td></tr>
