<?php 
/**
 * views template to output one 'row' of a view.
 * This code was generated by the views theming wizard
 * Date: Sun, 09/16/2007 - 05:09
 * View: all_video
 *
 * Variables available:
 * $view -- the entire view object. Important parts of this object are
 *   all_video, .
 * $view_type -- The type of the view. Probably 'page' or 'block' but could
 *   also be 'embed' or other string passed in from a custom view creator.
 * $node -- the raw data. This is not a real node object, but will contain
 *   the nid as well as other support fields that might be necessary.
 * $count -- the current row in the view (not TOTAL but for this page) starting
 *   from 0.
 * $stripe -- 'odd' or 'even', alternating. * $title -- Display the title of the node.
 * $title_label -- The assigned label for $title
 * $field_video_embed -- 
 * $field_video_embed_label -- The assigned label for $field_video_embed
 * $name -- This will display the author of the node.
 * $name_label -- The assigned label for $name
 * $created -- Display the post time of the node. The option field may be used to specify the custom date format as 
it's required by the date() function or if "as time ago" has been chosen to customize the granularity of the time 
interval.
 * $created_label -- The assigned label for $created
 * $body -- Display the Main Content.
 * $body_label -- The assigned label for $body
 *
 * This function goes in your views-list-all_video.tpl.php file
 */
 
$name_label = 'Submitted by: ';
 
 //now we add the stylesheet...
  drupal_add_css(path_to_theme() .'/views-list-all_video.css');
  
  ?>
<table class="view-all-video-table">
  <tr>
    <td colspan="2" class="view-data-title-td"><div class="view-field view-data-title"><?php print 
$title?></div>
    </td>
  </tr>

  <tr>
    <td class="view-data-field-video-embed-td"><div class="view-field view-data-field-video-embed">
      <?php print $field_video_embed?></div>
    </td>
    <td valign="top"><div class="view-label view-field-name"><?php print $name_label ?></div>
        <div class="view-field view-data-name"><?php print $name?></div>
        <br /><div class="view-field view-data-created"><?php print $created?></div>
        <br /><div class="view-field view-data-body"><?php print $body?></div>
        <?php if ($comment_count != '0') {?><br /><span class="first 
last comment_comments"><a href="/node/<?php print 
$node->nid?>#comments" title="Jump to the first comment of this 
posting." class="comment_comments"><?php echo $comment_count .' 
comment'; if ($comment_count > '1') echo 's';?></a></span>
<?php } else { ?>
        <br /><span class="first last comment_add"><a 
href="/comment/reply/<?php print $node->nid; ?>#comment-form" title="Add a new 
comment to this video." class="comment_add">Add new 
comment</a></span><?php } ?>

    </td>
  </tr>
</table>
