<?php 
/**
 * views template to output one 'row' of a view.
 * This code was generated by the views theming wizard
 * Date: Sun, 09/16/2007 - 04:40
 * View: most_recent_video
 *
 * Variables available:
 * $view -- the entire view object. Important parts of this object are
 *   most_recent_video, .
 * $view_type -- The type of the view. Probably 'page' or 'block' but could
 *   also be 'embed' or other string passed in from a custom view creator.
 * $node -- the raw data. This is not a real node object, but will contain
 *   the nid as well as other support fields that might be necessary.
 * $count -- the current row in the view (not TOTAL but for this page) starting
 *   from 0.
 * $stripe -- 'odd' or 'even', alternating. * $field_video_embed -- 
 * $field_video_embed_label -- The assigned label for $field_video_embed
 * $title -- Display the title of the node.
 * $title_label -- The assigned label for $title
 *
 * This function goes in your views-list-most_recent_video.tpl.php file
 */
 
 
 //now we add the stylesheet...
  drupal_add_css(path_to_theme() .'/views-list-most_recent_video.css');
  
  ?>
<div class="view-field view-data-field-video-embed">
  <?php print $field_video_embed?>
</div>

<div class="view-field view-data-title">
Now Playing: <?php print $title?>
</div>


